### ISSUE TITLE
Callbacks don't fire

### ISSUE THREAD

**Issue by speasley** [euvl/v-clipboard#2]
Following the example provided in the documentation, neither of the callbacks fire. Tested in Chrome 63.0.3239.84 and Safari 11.0.2.

**Comment by pandaljf** [comment]
So do I

**Comment by cksa** [comment]
so do i

**Comment by Heziode** [comment]
So do I

**Comment by euvl** [comment]
In vue 2.5+ or smth directive does not have access to component's context

**Comment by euvl** [comment]
This will be fixed in 2.0.0 but you will have to take a look in docs as far as the way callbacks are handled has changed.
